---
title: "index.rmd"
author: "Ethan Rosenbaum and Yujing Wang"
date: "2/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(haven)
library(dplyr)
library(ggplot2)
library(tidyverse)
```
## Chart 1: Density Curve of Death Rates
```{r}
testingdata <- read.csv("cases_deaths_and_testing_by_state.csv")
vaccinedata <- read.csv("covid19_vaccinations.csv")
data <- left_join(testingdata,vaccinedata)
data <- data[-c(36), ]
deaths <- as.numeric(data$Death.Rate.per.100000)
dens <- ggplot(data, aes(x=deaths, color = deaths)) +
  geom_density(color="darkblue", fill="lightblue", alpha = 0.9) +
  labs(title = "Density Curve of COVID-19 Deaths per 100,000",
       x = "Deaths per 100,000 Residents",
       y = "Density",
       subtitle = "Density of Deaths as a Result of COVID-19 Across Every State",
       caption = "Source: Center for Disease Control and Prevention: COVID Data Tracker")
dens
```
## Chart 2: Lollipop Chart of Testing Rates in Northeast
```{r}
caserate <- as.numeric(data$Case.Rate.per.100000)
testloll <- ggplot(data, aes(x = State.Territory, y = caserate))+
  geom_point(size=3, color ="lightblue") +
  geom_segment(aes(x=State.Territory, xend=State.Territory,
                   y=0, yend= caserate),
                   color = "darkblue")+
  scale_y_continuous(breaks = seq(0, 30000, 5000))
testloll
```
## Chart 3: COVID-19 Death Rate by State and Territory
```{r}
bar <- ggplot(data, aes(x = State.Territory, y = as.numeric(Death.Rate.per.100000))) +
  geom_bar(stat = "identity",
           fill = "lightcoral",
           alpha = 0.8)+
  labs(
    title = "COVID-19 Death Rate in the United States, by State",
    x = "State or Territory",
    y = "COVID-19 Death Rate per 100,000",
    subtitle = "COVID-19 Death Rate per 100,000 Residents",
    caption = "Source: Center for Disease Control and Prevention: COVID Data Tracker") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
bar
```
### Chart 4: 
```{r}
plot <- ggplot(data, aes(x = as.numeric(Case.Rate.per.100000), y = as.numeric(Doses.Delivered.per.100K))) +
  geom_point(stat = "identity",
             color = "firebrick",
             shape = "diamond") +
   labs(
    title = "COVID-19 Case and Dosage Rate in the United States",
    x = "COVID-19 Case Rate per 100,000 Residents",
    y = "COVID-19 Vaccine Dose Rate per 100,000 Residents",
    subtitle = "COVID-19 Case Rate Compared to Vaccine Dose Rate per 100,000 Residents by State or Territory",
    caption = "Source: Center for Disease Control and Prevention: COVID Data Tracker") 
plot
```

